"""inital migration

Revision ID: b6197b398a83
Revises: 
Create Date: 2018-09-19 17:06:52.273000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6197b398a83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('data_type', sa.String(length=64), nullable=True))
    op.add_column('patients', sa.Column('exp_data', sa.String(length=128), nullable=True))
    op.add_column('patients', sa.Column('expdata_exist', sa.Boolean(), nullable=True))
    op.add_column('patients', sa.Column('pro_name', sa.String(length=64), nullable=True))
    op.add_column('patients', sa.Column('public', sa.String(length=64), nullable=True))
    op.add_column('patients', sa.Column('ref_data', sa.String(length=128), nullable=True))
    op.add_column('patients', sa.Column('refdata_exist', sa.Boolean(), nullable=True))
    op.add_column('patients', sa.Column('sample_name', sa.String(length=128), nullable=True))
    op.add_column('patients', sa.Column('upl_name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_patients_sample_name'), 'patients', ['sample_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_sample_name'), table_name='patients')
    op.drop_column('patients', 'upl_name')
    op.drop_column('patients', 'sample_name')
    op.drop_column('patients', 'refdata_exist')
    op.drop_column('patients', 'ref_data')
    op.drop_column('patients', 'public')
    op.drop_column('patients', 'pro_name')
    op.drop_column('patients', 'expdata_exist')
    op.drop_column('patients', 'exp_data')
    op.drop_column('patients', 'data_type')
    # ### end Alembic commands ###
